services:
  db:
    image: postgres:16.1
    container_name: rcr-db
    hostname: rcr-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
    - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  rcr-back:
    build: .
    container_name: rcr-backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    ports:
    - "8080:8080"
    volumes:
      - ./src:/usr/src/app
    command: ["npm install && npx prisma db push --force-reset && npx prisma db seed && npm run start"]


