services:
  db:
    image: postgres:16.2
    container_name: rcr-db
    hostname: rcr-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data

  rcr-back:
    build: .
    container_name: rcr-backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    volumes:
      - ./src:/usr/src/app
    command: npm run start


